version: '3.8'
services:
  web:
    build:
      context: ../frontend
      args:
        REACT_APP_API_URL: http://localhost:3001/api
    depends_on:
      - api
    ports:
      - '8080:8080'
    labels:
      dev.ergomake.preview.replace-arg.REACT_APP_API_URL: '{{ ergomake.previewUrls.api }}/api'
  api:
    build: ../backend
    depends_on:
      - mongo
    ports:
      - '3001:3001'
    networks:
      - network-backend

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks:
      - network-backend

networks:
  network-backend:

volumes:
  mongodb_data:
