version: '3.8'
services:
  web:
    build:
      context: ../frontend
    ports:
      - '8080:8080'
    labels:
      dev.ergomake.env.replace-arg.REACT_APP_API_URL: 'https://{{ services.api.url }}/api'

  api:
    build: ../backend
    ports:
      - '3001:3001'

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017
